"""Scenario files (PRD §12.2): load, expand to Envelopes, preload, seeds and labels.

Dev 1's scripts import this module too, so the signatures below are frozen (PRD §16.1).

Timing rule: an item's occurred_at = start + at_min minutes + 10 s × (its position among the items of the same
list that share that at_min). Steps with `type` become Envelopes; steps with `action: step_up_respond` become a
StepUpAction (API mode) or a step_up_result Envelope with challenge_id "chl_direct" (direct mode).
"""
from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Literal

import yaml
from pydantic import ValidationError

from engine.common.ids import new_id
from engine.common.tokenize import tok
from engine.contracts import Context, Envelope, Label, StepUpResultPayload, Subject, validate_payload

DIRECT_CHALLENGE_ID = "chl_direct"
STEP_UP_SOURCE = "demo-bank-web"          # PRD §7.1: step_up_result is sent by demo-bank-web (generated by the API)
SAME_MINUTE_SPACING_S = 10
SEED_KINDS = ("cust", "acct", "dev", "ip", "phone", "email", "cid", "res", "mer")


@dataclass(frozen=True)
class StepUpAction:
    at: datetime
    channel: Literal["app", "phone"]
    as_identity: str
    decision: str | None          # "approve" | "deny" for channel phone
    direct_payload: dict          # StepUpResultPayload fields minus challenge_id


@dataclass(frozen=True)
class Scenario:
    id: str
    default_start: datetime
    raw: dict                     # parsed YAML


# ---------------------------------------------------------------------------- loading
def _parse_start(value) -> datetime:
    dt = value if isinstance(value, datetime) else datetime.fromisoformat(str(value))
    if dt.tzinfo is None:
        raise ValueError("default_start must carry a UTC offset")
    return dt


def _check_item(sc_id: str, where: str, item: dict, identities: dict, allow_action: bool) -> None:
    if not isinstance(item, dict) or not isinstance(item.get("at_min"), int | float):
        raise ValueError(f"{sc_id}: {where}: every item needs a numeric at_min")
    who = item.get("as")
    if who is not None and who not in identities:
        raise ValueError(f"{sc_id}: {where}: unknown identity {who!r}")
    if "type" in item:
        validate_payload(item["type"], item.get("payload") or {})
        Envelope.model_validate({"event_id": "evt_validate00", "event_type": item["type"], "source": item.get("source"),
                                 "occurred_at": "2026-01-01T00:00:00+00:00", "payload": item.get("payload") or {}})
    elif allow_action and item.get("action") == "step_up_respond":
        if who is None or item.get("channel") not in ("app", "phone"):
            raise ValueError(f"{sc_id}: {where}: step_up_respond needs `as` and channel app|phone")
        if item["channel"] == "phone" and item.get("decision") not in ("approve", "deny"):
            raise ValueError(f"{sc_id}: {where}: a phone step_up_respond needs decision approve|deny")
        StepUpResultPayload.model_validate({**(item.get("direct_payload") or {}), "challenge_id": DIRECT_CHALLENGE_ID})
    else:
        raise ValueError(f"{sc_id}: {where}: an item needs `type` (or `action: step_up_respond` in steps)")


def load_scenario(path: str) -> Scenario:
    """Parse and validate a scenario file. Raises ValueError / pydantic.ValidationError on a malformed file."""
    raw = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{path}: not a YAML mapping")
    for key in ("id", "default_start", "identities", "steps"):
        if key not in raw:
            raise ValueError(f"{path}: missing `{key}`")
    raw.setdefault("preload", [])
    raw.setdefault("seeds", [])
    raw.setdefault("labels", {"attack_id": None, "is_attack": False})
    raw["preload"] = raw["preload"] or []
    raw["seeds"] = raw["seeds"] or []
    sc_id = str(raw["id"])
    identities = raw["identities"] or {}
    for name, ident in identities.items():
        try:
            Subject.model_validate(ident.get("subject") or {})
            Context.model_validate(ident.get("context") or {})
        except (AttributeError, ValidationError) as exc:
            raise ValueError(f"{sc_id}: identity {name!r} is invalid: {exc}") from exc
    for i, item in enumerate(raw["preload"]):
        _check_item(sc_id, f"preload[{i}]", item, identities, allow_action=False)
    for i, item in enumerate(raw["steps"]):
        _check_item(sc_id, f"steps[{i}]", item, identities, allow_action=True)
    for s in raw["seeds"]:
        if s.get("kind") not in SEED_KINDS or not s.get("raw"):
            raise ValueError(f"{sc_id}: seed {s!r} needs a kind in {SEED_KINDS} and a raw value")
    if not isinstance(raw["labels"].get("is_attack"), bool):
        raise ValueError(f"{sc_id}: labels.is_attack must be true or false")
    sc = Scenario(id=sc_id, default_start=_parse_start(raw["default_start"]), raw=raw)
    # labels_for() tells preload from steps by content, so no step may look exactly like a preload item.
    clash = _signatures(sc, sc.raw["preload"]) & _signatures(sc, sc.raw["steps"])
    if clash:
        raise ValueError(f"{sc_id}: a step is identical to a preload item (same type, source, identity and payload)")
    return sc


# ---------------------------------------------------------------------------- expansion
def _times(items: list[dict], start: datetime) -> list[datetime]:
    seen: Counter = Counter()
    out = []
    for item in items:
        at = item["at_min"]
        out.append(start + timedelta(minutes=at, seconds=SAME_MINUTE_SPACING_S * seen[at]))
        seen[at] += 1
    return out


def _identity(sc: Scenario, name: str | None) -> tuple[dict, dict]:
    if name is None:
        return {}, {}
    ident = sc.raw["identities"][name]
    return dict(ident.get("subject") or {}), dict(ident.get("context") or {})


def _envelope(sc: Scenario, event_type: str, source: str, who: str | None, payload: dict, at: datetime) -> Envelope:
    subject, context = _identity(sc, who)
    return Envelope(event_id=new_id("evt"), event_type=event_type, source=source, occurred_at=at,
                    subject=Subject(**subject), context=Context(**context), payload=dict(payload))


def _step_up_envelope(sc: Scenario, item: dict, at: datetime) -> Envelope:
    payload = {**item["direct_payload"], "challenge_id": DIRECT_CHALLENGE_ID}
    return _envelope(sc, "step_up_result", STEP_UP_SOURCE, item["as"], payload, at)


def expand(sc: Scenario, start: datetime, mode: Literal["api", "direct"]) -> list[Envelope | StepUpAction]:
    """The scenario's steps in order. Direct mode turns every StepUpAction into a step_up_result Envelope."""
    if mode not in ("api", "direct"):
        raise ValueError(f"mode must be 'api' or 'direct', not {mode!r}")
    if start.tzinfo is None:
        raise ValueError("start must be timezone-aware")
    out: list[Envelope | StepUpAction] = []
    for item, at in zip(sc.raw["steps"], _times(sc.raw["steps"], start), strict=True):
        if "type" in item:
            out.append(_envelope(sc, item["type"], item["source"], item.get("as"), item.get("payload") or {}, at))
        elif mode == "direct":
            out.append(_step_up_envelope(sc, item, at))
        else:
            out.append(StepUpAction(at=at, channel=item["channel"], as_identity=item["as"], decision=item.get("decision"),
                                    direct_payload=dict(item["direct_payload"])))
    return out


def preload_envelopes(sc: Scenario, start: datetime) -> list[Envelope]:
    """The preload items as Envelopes, ordered by occurred_at (timing relative to the same start as the steps)."""
    if start.tzinfo is None:
        raise ValueError("start must be timezone-aware")
    envs = [_envelope(sc, item["type"], item["source"], item.get("as"), item.get("payload") or {}, at)
            for item, at in zip(sc.raw["preload"], _times(sc.raw["preload"], start), strict=True)]
    return sorted(envs, key=lambda e: e.occurred_at)


def seed_tokens(sc: Scenario) -> list[str]:
    return [tok(s["kind"], str(s["raw"])) for s in sc.raw["seeds"]]


# ---------------------------------------------------------------------------- labels
def _signature(event_type: str, source: str, subject: dict, context: dict, payload: dict) -> str:
    return json.dumps([event_type, source, Subject(**subject).model_dump(mode="json"),
                       Context(**context).model_dump(mode="json"), payload], sort_keys=True, default=str)


def _item_signature(sc: Scenario, item: dict) -> str:
    subject, context = _identity(sc, item.get("as"))
    if "type" in item:
        return _signature(item["type"], item["source"], subject, context, dict(item.get("payload") or {}))
    payload = {**item["direct_payload"], "challenge_id": DIRECT_CHALLENGE_ID}
    return _signature("step_up_result", STEP_UP_SOURCE, subject, context, payload)


def _signatures(sc: Scenario, items: list[dict]) -> set[str]:
    return {_item_signature(sc, item) for item in items}


def _envelope_signature(env: Envelope) -> str:
    return _signature(env.event_type, env.source, env.subject.model_dump(mode="json"), env.context.model_dump(mode="json"), env.payload)


def labels_for(sc: Scenario, envelopes: list[Envelope]) -> list[Label]:
    """One Label per envelope: steps get the scenario's `labels`, preload items are benign.

    An envelope is matched to its preload item or step by content (type, source, identity, payload), so
    preload and steps may be expanded with different starts. A foreign envelope raises ValueError.
    """
    preload = _signatures(sc, sc.raw["preload"])
    steps = _signatures(sc, sc.raw["steps"])
    cfg = sc.raw["labels"]
    is_attack = bool(cfg["is_attack"])
    attack_id = cfg.get("attack_id") if is_attack else None
    out = []
    for env in envelopes:
        sig = _envelope_signature(env)
        if sig in preload:
            out.append(Label(event_id=env.event_id, scenario=sc.id, is_attack=False, attack_id=None))
        elif sig in steps:
            out.append(Label(event_id=env.event_id, scenario=sc.id, is_attack=is_attack, attack_id=attack_id))
        else:
            raise ValueError(f"{sc.id}: envelope {env.event_id} ({env.event_type}) is not part of this scenario")
    return out
