// AUTO-GENERATED by scripts/gen_ts_types.py from engine/contracts.py and api/schemas.py. Do not edit.
// CONTRACT_VERSION 1.1.0

export type EventType = "login" | "mfa_change" | "mfa_challenge" | "sim_signal" | "kyc_result" | "profile_change" | "payee_added" | "transaction" | "cloud_audit" | "network_ids_alert" | "step_up_result";
export type Source = "demo-bank-web" | "cloud-audit" | "network-ids" | "simulator";
export type EntityKind = "cust" | "acct" | "dev" | "ip" | "phone" | "email" | "cid" | "res" | "mer" | "ses";
export type EdgeType = "OWNS" | "LOGGED_IN_FROM" | "CONNECTED_VIA" | "HAS_PHONE" | "ENROLLED" | "RESET" | "ADDED_PAYEE" | "SENT" | "ACTED_FROM" | "ACCESSED" | "TARGETED" | "SHARES_DEVICE";
export type Stage = "S0_RECON" | "S1_INITIAL_ACCESS" | "S2_CONTROL_TAKEOVER" | "S3_IDENTITY_MANIPULATION" | "S4_ESCALATION" | "S5_POSITIONING" | "S6_MONETIZATION";
export type DetectorId = "txn" | "behaviour" | "auth" | "kyc" | "cyber" | "netsec" | "graph";
export type Family = "transaction" | "identity" | "device" | "kyc" | "cyber" | "graph";
export type Band = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type Action = "ALLOW" | "CAPTCHA_CHALLENGE" | "STEP_UP_ANY_FACTOR" | "STEP_UP_TRUSTED_FACTOR" | "HOLD_OUTBOUND_PAYMENTS" | "FREEZE_NEW_PAYEES" | "BLOCK_PENDING_PAYMENTS" | "REVOKE_SESSIONS" | "OPEN_CASE_P2" | "OPEN_CASE_P1" | "SCAM_WARNING" | "COOLING_OFF_HOLD";
export type CaseStatus = "OPEN" | "INVESTIGATING" | "CONFIRMED_FRAUD" | "FALSE_POSITIVE" | "CLOSED";
export type Verdict = "CONFIRMED_FRAUD" | "FALSE_POSITIVE" | "INCONCLUSIVE";
export type Role = "analyst" | "lead" | "admin";
export type PaymentState = "normal" | "held" | "blocked";
export type PaymentOutcome = "completed" | "held" | "blocked";
export type StepUpMethod = "sms_otp" | "totp" | "device_push";
export type ChallengeStatus = "pending" | "passed" | "failed" | "timeout" | "denied_by_customer";
export type ReplayMode = "fused" | "siloed";
export type NetworkType = "residential" | "mobile" | "hosting" | "vpn" | "tor" | "unknown";

export const CONTRACT_VERSION = "1.1.0";
export const STAGE_ORDER = ["S0_RECON", "S1_INITIAL_ACCESS", "S2_CONTROL_TAKEOVER", "S3_IDENTITY_MANIPULATION", "S4_ESCALATION", "S5_POSITIONING", "S6_MONETIZATION"] as const;
export const BAND_ORDER = ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;
export const DETECTOR_FAMILY: Record<DetectorId, Family> = {"txn": "transaction", "behaviour": "identity", "auth": "device", "kyc": "kyc", "cyber": "cyber", "netsec": "cyber", "graph": "graph"};
export const ACTION_SEVERITY: Record<Action, number> = {"ALLOW": 0, "OPEN_CASE_P2": 0, "OPEN_CASE_P1": 0, "CAPTCHA_CHALLENGE": 1, "STEP_UP_ANY_FACTOR": 1, "STEP_UP_TRUSTED_FACTOR": 2, "HOLD_OUTBOUND_PAYMENTS": 2, "FREEZE_NEW_PAYEES": 3, "BLOCK_PENDING_PAYMENTS": 3, "REVOKE_SESSIONS": 3, "SCAM_WARNING": 1, "COOLING_OFF_HOLD": 2};
export const SEVERITY_HOLD = 2;

export interface ActionsRequest {
  actions: Action[];
  reason: string;
}

export interface AskRequest {
  question: string;
}

export interface AskResponse {
  answer: string;
  sentences: NarrativeSentence[];
  removed: number;
}

export interface AuditVerify {
  ok: boolean;
  rows: number;
  broken_at: number | null;
}

export interface BandThresholds {
  medium: number;
  high: number;
  critical: number;
}

export interface BatchRejected {
  event_id: string;
  code: string;
}

export interface BatchRequest {
  events: Envelope[];
}

export interface BatchResponse {
  accepted: number;
  rejected: BatchRejected[];
}

export interface BenchmarkReport {
  seed: number;
  days: number;
  families: Record<string, FamilyMetrics>;
  benign_customers: number;
  benign_flagged_high: number;
  false_positive_rate: number;
  false_declines_rate: number;
  alert_compression: number;
  txn_pr_auc: number;
  txn_roc_auc: number;
  txn_ece: number;
}

export interface Case {
  case_id: string;
  anchor_entity: string;
  customer: string | null;
  status: CaseStatus;
  band: Band;
  p_attack: number;
  log_odds: number;
  stages: Record<string, StageHit>;
  entities: string[];
  pattern_hits: string[];
  floors: string[];
  amount_at_risk_paise: number;
  payment_state: PaymentState;
  latest_actions: Action[];
  opened_at: string;
  updated_at: string;
  last_event_ts: string;
}

export interface CaseDetail {
  case: Case;
  summary: CaseSummary;
}

export interface CaseSummary {
  case_id: string;
  anchor_entity: string;
  customer: string | null;
  status: CaseStatus;
  band: Band;
  p_attack: number;
  stages_reached: Stage[];
  current_stage: Stage | null;
  latest_actions: Action[];
  payment_state: PaymentState;
  amount_at_risk_paise: number;
  updated_at: string;
}

export interface CaseUpdate {
  type: "case_update";
  case: CaseSummary;
  event_id: string;
  new_evidence_ids: string[];
  decision_id: string | null;
  step_up: StepUpRequest | null;
  payment_outcome: PaymentOutcome | null;
}

export interface CasesPage {
  items: CaseSummary[];
  next_cursor: string | null;
}

export interface ChallengeInfo {
  challenge_id: string;
  method: StepUpMethod;
  status: ChallengeStatus;
  created_at: string;
}

export interface ChallengeUpdate {
  type: "challenge_update";
  challenge_id: string;
  status: ChallengeStatus;
  case_id: string;
}

export interface CloudAuditPayload {
  actor_type: "support_console" | "service" | "admin";
  actor_identity: string;
  action: string;
  target_customer: string | null;
  src_ip: string;
  result: "success" | "failure";
}

export interface Context {
  ip: string | null;
  device_id: string | null;
  user_agent: string | null;
  city: string | null;
  lat: number | null;
  lon: number | null;
  asn: string | null;
  session_id: string | null;
  browser_timezone: string | null;
  locale: string | null;
  platform: string | null;
  webgl_renderer: string | null;
  screen: string | null;
  telemetry: Telemetry | null;
}

export interface Decision {
  decision_id: string;
  case_id: string;
  trigger_event_id: string;
  trigger_evidence_id: string | null;
  band: Band;
  p_attack: number;
  policy_rule: string;
  actions: Action[];
  actor: string;
  override_reason: string | null;
  created_at: string;
}

export interface DemoEmitRequest {
  event_type: EventType;
  subject: Subject;
  context: Context;
  payload: Record<string, unknown>;
}

export interface DemoEmitResponse {
  event_id: string;
}

export interface DetectorInfo {
  detector: DetectorId;
  family: Family;
  alpha: number;
  beta: number;
  reliability: number;
}

export interface Edge {
  src: string;
  dst: string;
  edge_type: EdgeType;
  confidence: number;
  first_seen: string;
  last_seen: string;
  count: number;
  source_event_ids: string[];
}

export interface Envelope {
  event_id: string;
  event_type: EventType;
  source: Source;
  occurred_at: string;
  schema_version: "1.0" | "1.1";
  subject: Subject;
  context: Context;
  payload: Record<string, unknown>;
}

export interface ErrorBody {
  error: ErrorDetail;
}

export interface ErrorDetail {
  code: string;
  message: string;
  request_id: string;
}

export interface EventAccepted {
  event_id: string;
  status: "accepted";
}

export interface Evidence {
  evidence_id: string;
  event_id: string;
  detector: DetectorId;
  detector_version: string;
  family: Family;
  stage: Stage;
  attack_technique: string | null;
  p: number;
  reliability: number;
  contribution: number;
  entities: string[];
  reasons: Reason[];
  shap: ShapItem[] | null;
  amount_paise: number | null;
  degraded: boolean;
  ts: string;
}

export interface Explanation {
  case_id: string;
  prior_log_odds: number;
  parts: ExplanationPart[];
  final_log_odds: number;
  p_attack: number;
  band: Band;
  floors: string[];
  narrative: NarrativeSentence[];
  shap_by_evidence: Record<string, ShapItem[]>;
  seed_paths: string[][];
}

export interface ExplanationPart {
  part_id: string;
  kind: "prior" | "evidence" | "pattern" | "floor";
  label: string;
  detector: DetectorId | null;
  stage: Stage | null;
  contribution: number;
  running_log_odds: number;
  running_p: number;
  ts: string | null;
}

export interface FamilyMetrics {
  instances: number;
  caught_fused: number;
  caught_siloed: number;
  median_lead_time_s: number | null;
}

export interface FeedbackRequest {
  verdict: Verdict;
  note: string | null;
}

export interface FeedbackResult {
  case_id: string;
  verdict: Verdict;
  reliability_before: Record<string, number>;
  reliability_after: Record<string, number>;
  seeds_added: string[];
  status_after: CaseStatus;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  edge_type: EdgeType;
  confidence: number;
}

export interface GraphElements {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface GraphNode {
  id: string;
  label: string;
  kind: EntityKind;
  seed: boolean;
  in_case: boolean;
}

export interface Health {
  status: "ok";
  db: boolean;
  pipeline_ready: boolean;
  contract_version: string;
  model_sha256: string | null;
}

export interface KycResultPayload {
  liveness_score: number;
  face_match_score: number;
  doc_tamper_score: number;
  injection_suspected: boolean;
  reason: "onboarding" | "re_verification";
}

export interface Label {
  event_id: string;
  scenario: string;
  is_attack: boolean;
  attack_id: string | null;
}

export interface LiveMetrics {
  cases_open: number;
  critical_open: number;
  money_protected_paise: number;
  alert_compression: number;
}

export interface LoginPayload {
  result: "success" | "failure";
  auth_method: "password" | "password+otp" | "password+push";
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface MetricsSummary {
  benchmark: BenchmarkReport | null;
  live: LiveMetrics;
}

export interface MfaChallengePayload {
  method: StepUpMethod;
  result: "passed" | "failed" | "ignored";
}

export interface MfaChangePayload {
  factor: "sms" | "totp" | "device_push";
  action: "add" | "replace" | "remove";
  new_phone: string | null;
}

export interface NarrativeSentence {
  text: string;
  cites: string[];
}

export interface NetworkIdsAlertPayload {
  src_ip: string;
  dest_ip: string;
  dest_port: number;
  signature_id: number;
  signature: string;
  category: string;
  severity: number;
}

export interface PayeeAddedPayload {
  payee_account: string;
  payee_name_match: boolean | null;
  nickname: string;
}

export interface PaymentStatus {
  outcome: PaymentOutcome | "pending";
}

export interface PendingChallenge {
  challenge_id: string;
  method: StepUpMethod;
  expires_at: string;
  masked_destination: string;
}

export interface PendingResponse {
  challenge: PendingChallenge | null;
}

export interface ProfileChangePayload {
  field: "password" | "email" | "phone" | "address";
}

export interface Reason {
  code: string;
  detail: string | null;
}

export interface ReplayPoint {
  ts: string;
  evidence_id: string;
  p: number;
  band: string;
  actions: Action[];
  severity: number;
}

export interface ReplayRequest {
  ablate: DetectorId[];
  mode: ReplayMode;
}

export interface ReplayResult {
  replay_id: string;
  case_id: string;
  mode: ReplayMode;
  ablated: DetectorId[];
  timeline: ReplayPoint[];
  eip: ReplayPoint | null;
  baseline_eip: ReplayPoint | null;
  lead_time_s: number | null;
  lead_time_lost_s: number | null;
  money_protected_paise: number;
}

export interface RespondRequest {
  code: string | null;
  decision: "approve" | "deny" | null;
}

export interface RespondResponse {
  status: ChallengeStatus;
}

export interface RunRequest {
  speed: number;
}

export interface RunResponse {
  run_id: string;
}

export interface ShapItem {
  feature: string;
  value: number;
  shap: number;
}

export interface SimSignalPayload {
  sim_change_age_h: number;
}

export interface SimulationResult {
  thresholds: BandThresholds;
  attacks_total: number;
  attacks_caught: number;
  benign_customers_total: number;
  benign_customers_flagged: number;
  legit_payments_total: number;
  legit_payments_stopped: number;
  money_protected_paise: number;
  median_lead_time_s: number | null;
}

export interface SmsInbox {
  messages: SmsMessage[];
}

export interface SmsMessage {
  text: string;
  at: string;
}

export interface StageHit {
  ts: string;
  evidence_id: string;
}

export interface StatusOk {
  status: "ok";
}

export interface StepUpRequest {
  case_id: string;
  customer: string;
  method_class: "any" | "trusted";
  reason_event_id: string;
}

export interface StepUpResultPayload {
  challenge_id: string;
  method: StepUpMethod;
  result: "passed" | "failed" | "timeout" | "denied_by_customer";
  factor_age_h: number;
}

export interface StoredEvent {
  event_id: string;
  event_type: EventType;
  source: Source;
  occurred_at: string;
  received_at: string;
  customer: string | null;
  account: string | null;
  ip: string | null;
  device: string | null;
  asn: string | null;
  city: string | null;
  lat: number | null;
  lon: number | null;
  payload: Record<string, unknown>;
  entity_tokens: string[];
  session: string | null;
  network_type: NetworkType | null;
  network_source: string | null;
  network_confidence: number | null;
  ip_timezone: string | null;
  browser_timezone: string | null;
  locale: string | null;
  platform: string | null;
  webgl_renderer: string | null;
  screen: string | null;
  telemetry: Telemetry | null;
}

export interface Subject {
  customer_ref: string | null;
  account_ref: string | null;
}

export interface Telemetry {
  pointer_type: "mouse" | "touch" | "pen" | null;
  keystroke_interval_ms_mean: number | null;
  keystroke_interval_ms_std: number | null;
  paste_in_sensitive_field: boolean | null;
  payment_screen_dwell_s: number | null;
  beneficiary_screen_dwell_s: number | null;
  screen_resolution_changes: number | null;
  remote_access_demo: boolean | null;
  active_call_demo: boolean | null;
}

export interface Timeline {
  evidence: Evidence[];
  decisions: Decision[];
  challenges: ChallengeInfo[];
}

export interface TokenResponse {
  access_token: string;
  token_type: "bearer";
  expires_in: number;
  role: Role;
}

export interface TransactionPayload {
  amount_paise: number;
  payee_account: string;
  channel: "UPI" | "IMPS" | "NEFT" | "CARD";
}
