"""/v1/demo/* (PRD §9.5), mounted only when DEMO_MODE=1. The bank demo app never holds a signing secret: it calls
/demo/emit and the server builds, signs and ingests the Envelope. /run plays a scenario into the API (autopilot);
/reset runs the §12.3 demo reset and rebuilds the in-memory pipeline. /baseline, /live and /reset-live serve the
live two-laptop demo: snapshot the current data once, watch only the cases created after it, and undo them in seconds."""
from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timedelta, timezone
from typing import Literal

import httpx
from fastapi import APIRouter, Depends, Query, Request

from api import autopilot, demo_baseline, demo_reset, queries, scenario_source, stepup
from api.demo_identities import REGISTERED_DEVICE, demo_state, fill_context, phone_key
from api.errors import ApiError
from api.pipeline_factory import make_pipeline
from api.routers.ingest import ingest_server_side, server_headers
from api.schemas import (
    DemoEmitRequest,
    DemoEmitResponse,
    PaymentStatus,
    PendingChallenge,
    PendingResponse,
    RespondRequest,
    RespondResponse,
    RunRequest,
    RunResponse,
    SmsInbox,
    SmsMessage,
    StatusOk,
)
from api.security import Principal, require_role
from engine.common.ids import new_id
from engine.common.tokenize import tok
from engine.contracts import Envelope, summarize

router = APIRouter(prefix="/v1/demo", tags=["demo"])
log = logging.getLogger("fraudmesh.demo")
IST = timezone(timedelta(hours=5, minutes=30))

# event types the bank web app may send (PRD §7.1 "Sent by demo-bank-web"); step_up_result is generated by the API only
BANK_APP_EVENTS = {"login", "mfa_change", "mfa_challenge", "kyc_result", "profile_change", "payee_added", "transaction"}


@router.post("/emit", response_model=DemoEmitResponse)
async def emit(body: DemoEmitRequest, request: Request) -> DemoEmitResponse:
    if body.event_type not in BANK_APP_EVENTS:
        raise ApiError("FORBIDDEN", f"the bank app cannot emit {body.event_type}")
    context = fill_context(body.context.model_dump(exclude_none=True))
    now = datetime.now(IST)
    if body.event_type == "login":
        await _ids_sensor(request.app, body.subject.customer_ref, context, now)
    env = Envelope(event_id=new_id("evt"), event_type=body.event_type, source="demo-bank-web",
                   occurred_at=now, subject=body.subject, context=context, payload=body.payload)
    await ingest_server_side(request.app, env)            # also records demo state (raw phone/context) in memory
    return DemoEmitResponse(event_id=env.event_id)


IDS_REALERT = timedelta(minutes=30)


async def _ids_sensor(app, customer_ref: str | None, context: dict, now: datetime) -> None:
    """Demo network sensor (stands in for Suricata, PRD §7.4): a login to a customer's account from a device that is
    not their registered one comes after password-guessing traffic from that IP, so the sensor raises the same
    credential-stuffing alert as scenarios/midnight_ato.yaml step 1, a few seconds before the login, once per IP per
    30 min (none when an alert for that IP is already stored, e.g. from scripts/send_signal.py ids). Logins from the
    customer's own registered device raise nothing."""
    ip, device = context.get("ip"), context.get("device_id")
    if not ip or not customer_ref or device == REGISTERED_DEVICE.get(customer_ref):
        return
    last = demo_state.ids_alerted.get(ip)
    if last is not None and now - last < IDS_REALERT:
        return
    if await asyncio.to_thread(queries.recent_ids_alert, tok("ip", ip), now - IDS_REALERT):
        return                                                  # the sensor (or a replayed alert) already saw this IP
    demo_state.ids_alerted[ip] = now
    alert = Envelope(event_id=new_id("evt"), event_type="network_ids_alert", source="network-ids",
                     occurred_at=now - timedelta(seconds=3), context={"ip": ip},
                     payload={"src_ip": ip, "dest_ip": "10.0.1.20", "dest_port": 443, "signature_id": 9000001,
                              "signature": "FM LOCAL credential stuffing against /api/login",
                              "category": "Attempted User Privilege Gain", "severity": 2})
    await ingest_server_side(app, alert)


@router.get("/payment-status/{event_id}", response_model=PaymentStatus)
async def payment_status(event_id: str) -> PaymentStatus:
    outcome = await asyncio.to_thread(queries.payment_outcome, event_id)
    return PaymentStatus(outcome=outcome or "pending")


@router.get("/step-up/pending", response_model=PendingResponse)
async def pending(customer_ref: str = Query(min_length=1, max_length=64),
                  channel: Literal["app", "phone"] = "app") -> PendingResponse:
    info = await asyncio.to_thread(stepup.pending_for, tok("cust", customer_ref), channel)
    if info is None:
        return PendingResponse(challenge=None)
    return PendingResponse(challenge=PendingChallenge(challenge_id=info["challenge_id"], method=info["method"],
                                                      expires_at=info["expires_at"], masked_destination=info["masked_destination"]))


@router.get("/sms-inbox", response_model=SmsInbox)
async def sms_inbox(phone: str = Query(min_length=4, max_length=32)) -> SmsInbox:
    msgs = demo_state.inbox.get(phone_key(phone), [])
    return SmsInbox(messages=[SmsMessage(text=m.text, at=m.at) for m in msgs])


@router.post("/step-up/{challenge_id}/respond", response_model=RespondResponse)
async def respond(challenge_id: str, body: RespondRequest, request: Request) -> RespondResponse:
    if (body.code is None) == (body.decision is None):
        raise ApiError("VALIDATION_FAILED", "send exactly one of code or decision")
    info, changed, age = await asyncio.to_thread(stepup.resolve, challenge_id, body.code, body.decision)
    if changed:
        await stepup.emit_result(request.app, info, age)
    return RespondResponse(status=info["status"])


@router.post("/run/{scenario_id}", response_model=RunResponse)
async def run(scenario_id: str, body: RunRequest, request: Request, p: Principal = Depends(require_role("admin"))) -> RunResponse:
    """Autopilot: play the scenario's steps into this API as a background task, start = now (PRD §9.5)."""
    if scenario_source.scenario_path(scenario_id) is None:
        raise ApiError("NOT_FOUND", f"unknown scenario {scenario_id}")
    app = request.app
    st = autopilot.RunState(run_id=new_id("run"), scenario=scenario_id, speed=body.speed)

    async def _go() -> None:
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(transport=transport, base_url="http://autopilot", timeout=30) as client:
            await autopilot.play(client, scenario_id, datetime.now(IST), body.speed, server_headers, st,
                                 label_sink=lambda sc, envs: app.state.store.save_labels(scenario_source.labels_for(sc, envs)))
        log.info("autopilot %s %s: %s", st.run_id, scenario_id, st.status)

    app.state.runs[st.run_id] = (st, asyncio.create_task(_go(), name=st.run_id))
    await asyncio.to_thread(app.state.store.append_audit, p.user_id, "DEMO_RUN", st.run_id,
                            {"scenario": scenario_id, "speed": body.speed})
    return RunResponse(run_id=st.run_id)


@router.post("/reset", response_model=StatusOk)
async def reset(request: Request, p: Principal = Depends(require_role("admin"))) -> StatusOk:
    """PRD §12.3 reset, then rebuild this process's Pipeline (startup) and demo state, like a worker restart."""
    app = request.app
    async with app.state.reset_lock:
        for st, task in app.state.runs.values():                   # stop autopilots first
            st.status = "cancelled"
            task.cancel()
        app.state.runs.clear()
        await app.state.worker.drain()
        summary = await asyncio.to_thread(demo_reset.reset_demo, app.state.store, None, log.info)
        pipeline = make_pipeline(app.state.store)
        await asyncio.to_thread(pipeline.startup)
        app.state.pipeline = pipeline
        demo_state.reset()
        await asyncio.to_thread(app.state.store.append_audit, p.user_id, "DEMO_RESET", "demo",
                                {k: v for k, v in summary.items() if k != "seeds"})
        await asyncio.to_thread(demo_baseline.save_baseline)        # the fresh state is what /reset-live returns to
    await app.state.broadcaster.broadcast({"type": "demo_reset", "scope": "full"})
    return StatusOk()


# ------------------------------------------------------------------ live two-laptop demo
@router.post("/baseline")
async def save_baseline(request: Request, p: Principal = Depends(require_role("admin"))) -> dict:
    """Snapshot the current data as the demo starting point (what Reset returns to)."""
    async with request.app.state.reset_lock:
        await request.app.state.worker.drain()
        meta = await asyncio.to_thread(demo_baseline.save_baseline)
        await asyncio.to_thread(request.app.state.store.append_audit, p.user_id, "DEMO_BASELINE_SAVED", "demo", meta)
    return meta


@router.get("/live")
async def live(request: Request, p: Principal = Depends(require_role("analyst"))) -> dict:
    """The live demo: cases created or changed after the baseline, most recent first."""
    store = request.app.state.store
    ids = await asyncio.to_thread(demo_baseline.demo_case_ids)
    cases = [c for c in await asyncio.gather(*(asyncio.to_thread(store.get_case, i) for i in ids)) if c is not None]
    return {"baseline": await asyncio.to_thread(demo_baseline.info),
            "cases": [summarize(c).model_dump(mode="json") for c in cases]}


@router.post("/reset-live")
async def reset_live(request: Request, p: Principal = Depends(require_role("admin"))) -> dict:
    """Undo the live demo: restore the baseline snapshot (seconds) and rebuild the in-memory pipeline from it. The
    background and benchmark data are not regenerated or re-scored."""
    app = request.app
    t0 = datetime.now()
    async with app.state.reset_lock:
        for st, task in app.state.runs.values():
            st.status = "cancelled"
            task.cancel()
        app.state.runs.clear()
        await app.state.worker.drain()
        try:
            restored = await asyncio.to_thread(demo_baseline.restore_baseline)
        except LookupError as e:
            raise ApiError("NOT_FOUND", "no demo baseline saved yet: save one first") from e
        pipeline = make_pipeline(app.state.store)
        await asyncio.to_thread(pipeline.startup)
        app.state.pipeline = pipeline
        demo_state.reset()
        await asyncio.to_thread(app.state.store.append_audit, p.user_id, "DEMO_RESET_LIVE", "demo", restored)
    # every open console (any page, any laptop) drops its cached cases and reloads: the demo case is gone everywhere
    await app.state.broadcaster.broadcast({"type": "demo_reset", "scope": "live"})
    return {"status": "ok", "seconds": round((datetime.now() - t0).total_seconds(), 1), "baseline": restored}
