"""/v1/demo/* (PRD §9.5), mounted only when DEMO_MODE=1. The bank demo app never holds a signing secret: it calls
/demo/emit and the server builds, signs and ingests the Envelope. run/reset arrive in D1-P5."""
from __future__ import annotations

import asyncio
from datetime import datetime, timedelta, timezone
from typing import Literal

from fastapi import APIRouter, Depends, Query, Request

from api import queries, stepup
from api.demo_identities import demo_state, fill_context, phone_key
from api.errors import ApiError
from api.routers.ingest import ingest_server_side
from api.schemas import (
    DemoEmitRequest,
    DemoEmitResponse,
    PaymentStatus,
    PendingChallenge,
    PendingResponse,
    RespondRequest,
    RespondResponse,
    RunRequest,
    RunResponse,
    SmsInbox,
    SmsMessage,
    StatusOk,
)
from api.security import Principal, require_role
from engine.common.ids import new_id
from engine.common.tokenize import tok
from engine.contracts import Envelope

router = APIRouter(prefix="/v1/demo", tags=["demo"])
IST = timezone(timedelta(hours=5, minutes=30))

# event types the bank web app may send (PRD §7.1 "Sent by demo-bank-web"); step_up_result is generated by the API only
BANK_APP_EVENTS = {"login", "mfa_change", "mfa_challenge", "kyc_result", "profile_change", "payee_added", "transaction"}


@router.post("/emit", response_model=DemoEmitResponse)
async def emit(body: DemoEmitRequest, request: Request) -> DemoEmitResponse:
    if body.event_type not in BANK_APP_EVENTS:
        raise ApiError("FORBIDDEN", f"the bank app cannot emit {body.event_type}")
    context = fill_context(body.context.model_dump(exclude_none=True))
    env = Envelope(event_id=new_id("evt"), event_type=body.event_type, source="demo-bank-web",
                   occurred_at=datetime.now(IST), subject=body.subject, context=context, payload=body.payload)
    await ingest_server_side(request.app, env)
    cust = demo_state.remember(body.subject.customer_ref, context)
    if cust and body.event_type == "mfa_change" and body.payload.get("factor") == "sms" and body.payload.get("new_phone"):
        demo_state.phone[cust] = str(body.payload["new_phone"])
    return DemoEmitResponse(event_id=env.event_id)


@router.get("/payment-status/{event_id}", response_model=PaymentStatus)
async def payment_status(event_id: str) -> PaymentStatus:
    outcome = await asyncio.to_thread(queries.payment_outcome, event_id)
    return PaymentStatus(outcome=outcome or "pending")


@router.get("/step-up/pending", response_model=PendingResponse)
async def pending(customer_ref: str = Query(min_length=1, max_length=64),
                  channel: Literal["app", "phone"] = "app") -> PendingResponse:
    info = await asyncio.to_thread(stepup.pending_for, tok("cust", customer_ref), channel)
    if info is None:
        return PendingResponse(challenge=None)
    return PendingResponse(challenge=PendingChallenge(challenge_id=info["challenge_id"], method=info["method"],
                                                      expires_at=info["expires_at"], masked_destination=info["masked_destination"]))


@router.get("/sms-inbox", response_model=SmsInbox)
async def sms_inbox(phone: str = Query(min_length=4, max_length=32)) -> SmsInbox:
    msgs = demo_state.inbox.get(phone_key(phone), [])
    return SmsInbox(messages=[SmsMessage(text=m.text, at=m.at) for m in msgs])


@router.post("/step-up/{challenge_id}/respond", response_model=RespondResponse)
async def respond(challenge_id: str, body: RespondRequest, request: Request) -> RespondResponse:
    if (body.code is None) == (body.decision is None):
        raise ApiError("VALIDATION_FAILED", "send exactly one of code or decision")
    info, changed, age = await asyncio.to_thread(stepup.resolve, challenge_id, body.code, body.decision)
    if changed:
        await stepup.emit_result(request.app, info, age)
    return RespondResponse(status=info["status"])


@router.post("/run/{scenario_id}", response_model=RunResponse)
async def run(scenario_id: str, body: RunRequest, p: Principal = Depends(require_role("admin"))) -> RunResponse:
    return RunResponse(run_id=new_id("run"))          # D1-P5: autopilot


@router.post("/reset", response_model=StatusOk)
async def reset(p: Principal = Depends(require_role("admin"))) -> StatusOk:
    return StatusOk()                                 # D1-P5: truncate + reload
