"""Generate web/src/types/contracts.ts (and the bank-demo copy) from the Pydantic models (PRD §9, §11).

Sources: every model and Literal alias in engine/contracts.py plus the API wrappers in api/schemas.py.
Field names stay snake_case. Every property is emitted as required, because responses always serialise every field.
Usage: python scripts/gen_ts_types.py
"""
from __future__ import annotations

import inspect
import json
import sys
import typing
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pydantic import BaseModel  # noqa: E402

import api.schemas as api_schemas  # noqa: E402
import engine.contracts as contracts  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TARGETS = [ROOT / "web" / "src" / "types" / "contracts.ts", ROOT / "bank-demo" / "src" / "types" / "contracts.ts"]


def literal_aliases() -> dict[str, tuple[str, ...]]:
    out = {}
    for name, obj in vars(contracts).items():
        if typing.get_origin(obj) is typing.Literal:
            out[name] = tuple(typing.get_args(obj))
    return out


def models(module) -> list[type[BaseModel]]:
    return [obj for name, obj in vars(module).items()
            if inspect.isclass(obj) and issubclass(obj, BaseModel) and obj.__module__ == module.__name__ and not name.startswith("_")]


class Converter:
    def __init__(self, aliases: dict[str, tuple[str, ...]]) -> None:
        self.by_values = {frozenset(v): k for k, v in aliases.items()}

    def ts(self, s: dict) -> str:
        if "$ref" in s:
            return s["$ref"].rsplit("/", 1)[1]
        if "enum" in s:
            alias = self.by_values.get(frozenset(s["enum"]))
            return alias or " | ".join(json.dumps(v) for v in s["enum"])
        if "const" in s:
            return json.dumps(s["const"])
        for key in ("anyOf", "oneOf"):
            if key in s:
                parts = []
                for sub in s[key]:
                    t = self.ts(sub)
                    if t not in parts:
                        parts.append(t)
                return " | ".join(parts)
        t = s.get("type")
        if t == "string":
            return "string"
        if t in ("integer", "number"):
            return "number"
        if t == "boolean":
            return "boolean"
        if t == "null":
            return "null"
        if t == "array":
            if "prefixItems" in s:
                return "[" + ", ".join(self.ts(x) for x in s["prefixItems"]) + "]"
            inner = self.ts(s.get("items", {}))
            return f"({inner})[]" if "|" in inner else f"{inner}[]"
        if t == "object":
            if "properties" in s:
                return "{ " + "; ".join(f"{k}: {self.ts(v)}" for k, v in s["properties"].items()) + " }"
            extra = s.get("additionalProperties")
            return f"Record<string, {self.ts(extra) if isinstance(extra, dict) and extra else 'unknown'}>"
        return "unknown"

    def interface(self, name: str, s: dict) -> str:
        lines = [f"export interface {name} {{"]
        for prop, sub in s.get("properties", {}).items():
            lines.append(f"  {prop}: {self.ts(sub)};")
        lines.append("}")
        return "\n".join(lines)


def generate() -> str:
    aliases = literal_aliases()
    conv = Converter(aliases)
    defs: dict[str, dict] = {}
    for m in models(contracts) + models(api_schemas):
        schema = m.model_json_schema(mode="serialization", ref_template="#/$defs/{model}")
        defs.update(schema.pop("$defs", {}))
        defs[m.__name__] = schema
    out = ["// AUTO-GENERATED by scripts/gen_ts_types.py from engine/contracts.py and api/schemas.py. Do not edit.",
           f"// CONTRACT_VERSION {contracts.CONTRACT_VERSION}", ""]
    for name, values in aliases.items():
        out.append(f"export type {name} = {' | '.join(json.dumps(v) for v in values)};")
    out.append("")
    out.append(f"export const CONTRACT_VERSION = {json.dumps(contracts.CONTRACT_VERSION)};")
    out.append(f"export const STAGE_ORDER = {json.dumps(list(contracts.STAGE_ORDER))} as const;")
    out.append(f"export const BAND_ORDER = {json.dumps(list(contracts.BAND_ORDER))} as const;")
    out.append(f"export const DETECTOR_FAMILY: Record<DetectorId, Family> = {json.dumps(contracts.DETECTOR_FAMILY)};")
    out.append(f"export const ACTION_SEVERITY: Record<Action, number> = {json.dumps(contracts.ACTION_SEVERITY)};")
    out.append(f"export const SEVERITY_HOLD = {contracts.SEVERITY_HOLD};")
    out.append("")
    for name in sorted(defs):
        out.append(conv.interface(name, defs[name]))
        out.append("")
    return "\n".join(out)


def main() -> None:
    text = generate()
    for target in TARGETS:
        if target.parent.parent.parent.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            print("wrote", target.relative_to(ROOT))


if __name__ == "__main__":
    main()
